Traceback (most recent call last):
  File "/net/tscratch/people/plgmpniak/LSC_dim_reduction/LSC_Dimensionality_Reduction/scripts/pca_cpu.py", line 22, in <module>
    X = np.load(DATA_PATH / 'X_norm.npz')['X']
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/dimred_env/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 261, in __getitem__
    raise KeyError(f"{key} is not a file in the archive")
KeyError: 'X is not a file in the archive'
